/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casesimulator;

import java.awt.Color;

/**
 *
 * @author egor
 */
public class cases extends javax.swing.JFrame {

    int caseID;
    
    int weapons[] = new int[13];
    
    Color weaponsColor[] = new Color[13];
    
    public void getCaseWeapons(int caseID) {
        if(caseID == 13) {
            weaponsColor[0] = Color.BLUE;
            weaponsColor[1] = Color.BLUE;
            weaponsColor[2] = Color.BLUE;
            weaponsColor[3] = Color.MAGENTA;
            weaponsColor[4] = Color.RED;
            weaponsColor[5] = Color.YELLOW;
            weaponsColor[6] = Color.YELLOW;
            weaponsColor[7] = Color.YELLOW;
            weaponsColor[8] = Color.YELLOW;
            weaponsColor[9] = Color.YELLOW;
            weaponsColor[10] = Color.YELLOW;
            weaponsColor[11] = Color.YELLOW;
            weaponsColor[12] = Color.YELLOW;
        }
    }
    
    /**
     * Creates new form cases
     */
    public cases(int caseID) {
        this.caseID = caseID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
